[package]
name = "test-vfs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8"
sqlite-vfs = { path = "../", default-features = false, features = ["sqlite_test", "syscall", "loadext"] }
