[package]
name = "test-vfs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sqlite-vfs = { path = "../", default-features = false, features = ["sqlite_test"] }
